name: CI build_ext

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #install the environment and all dependencies
      - name: install env
        run: $CONDA/bin/conda env update --file bte.yml --name base
      # compile the extension
      - name: build_ext
        run: python3 setup.py build_ext --inplace

      # assert that the compiled library is importable
      - name: import test
        run: python3 -c "import mat"
