name: CI build_ext

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #install the environment and all dependencies then build the extension
      - name: fetch usher
        run: |
          git pull --recurse-submodules
          git submodule update --init
      - name: install env
        run: |
          $CONDA/bin/conda env create --file bte.yml --no-default-packages
          eval "$(conda shell.bash hook)"
          conda activate bte
          python3 setup.py build_ext --inplace
          python3 -m unittest run_test.py
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      #install the environment and all dependencies then build the extension
      - name: fetch usher
        run: |
          git pull --recurse-submodules
          git submodule update --init
      - name: install env
        run: |
          $CONDA/bin/conda env create --file bte.yml --no-default-packages
          eval "$(conda shell.bash hook)"
          conda activate bte
          python3 setup.py build_ext --inplace
          python3 -m unittest run_test.py
