name: CI build_ext

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #install the environment and all dependencies then build the extension
      - name: fetch usher
        run: |
          git pull --recurse-submodules
          git submodule update --init
      - name: install env
        run: |
          $CONDA/bin/conda env update --file bte.yml --name base
          eval "$(conda shell.bash hook)"
          conda activate base
          conda upgrade -c conda-forge --all
          python3 setup.py build_ext --inplace

      # assert that the compiled library is importable
      - name: import test
        run: python3 -c "import mat"
